name: DevSecOps Pipeline

on:
  workflow_dispatch:

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Secret Scanning
      - name: Git Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Maven build
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true

      # SonarCloud scanning
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=amarnathsaha
            -Dsonar.projectKey=amarnathsaha_spring-boot-hello-world
            -Dsonar.verbose=true
            -Dsonar.sources=src/main/java/
            -Dsonar.language=java
            -Dsonar.java.binaries=./target/classes
